<recipetype:extendedcrafting:table>.addShaped("d9008895-dafd-4bc7-949d-31f52d81719a", 0, <item:kubejs:compressed_compression_block>, [
	[<item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_slime_block>, <item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_slime_block>, <item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_slime_block>, <item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_slime_block>, <item:compressedblocks:c7_dirt>], 
	[<item:compressedblocks:c5_slime_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_slime_block>], 
	[<item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:septuple_crated_clay_ball>, <item:compressedblocks:c8_netherrack>, <item:compressedblocks:octuple_crated_sugar_cane>, <item:compressedblocks:c8_netherrack>, <item:compressedblocks:septuple_crated_clay_ball>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c7_dirt>], 
	[<item:compressedblocks:c5_slime_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c7_end_stone>, <item:compressedblocks:octuple_crated_rotten_flesh>, <item:compressedblocks:c7_end_stone>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_slime_block>], 
	[<item:compressedblocks:octuple_crated_sugar_cane>, <item:compressedblocks:septuple_crated_clay_ball>, <item:compressedblocks:c8_netherrack>, <item:compressedblocks:octuple_crated_rotten_flesh>, <item:compressedblocks:sextuple_crated_nether_star>, <item:compressedblocks:octuple_crated_rotten_flesh>, <item:compressedblocks:c8_netherrack>, <item:compressedblocks:septuple_crated_clay_ball>, <item:compressedblocks:octuple_crated_sugar_cane>], 
	[<item:compressedblocks:c5_slime_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c7_end_stone>, <item:compressedblocks:octuple_crated_rotten_flesh>, <item:compressedblocks:c7_end_stone>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_slime_block>], 
	[<item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:septuple_crated_clay_ball>, <item:compressedblocks:c8_netherrack>, <item:compressedblocks:octuple_crated_sugar_cane>, <item:compressedblocks:c8_netherrack>, <item:compressedblocks:septuple_crated_clay_ball>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c7_dirt>], 
	[<item:compressedblocks:c5_slime_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_magma_block>, <item:compressedblocks:c6_obsidian>, <item:compressedblocks:c5_slime_block>], 
	[<item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_slime_block>, <item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_slime_block>, <item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_slime_block>, <item:compressedblocks:c7_dirt>, <item:compressedblocks:c5_slime_block>, <item:compressedblocks:c7_dirt>]
]);