<recipetype:extendedcrafting:table>.addShaped(0, <item:lava:infinity_helmet>, [
	[<item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>], 
	[<item:kubejs:compressed_compression_block>, <item:lava:infinity_shard>, <item:lava:infinity_shard>, <item:lava:infinity_shard>, <item:extendedcrafting:ultimate_singularity>, <item:lava:infinity_shard>, <item:lava:infinity_shard>, <item:lava:infinity_shard>, <item:kubejs:compressed_compression_block>], 
	[<item:kubejs:compressed_compression_block>, <item:lava:infinity_shard>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:lava:infinity_shard>, <item:kubejs:compressed_compression_block>], 
	[<item:kubejs:compressed_compression_block>, <item:lava:infinity_shard>, <item:kubejs:compressed_compression_block>, <item:compressedblocks:c8_redstone_block>, <item:compressedblocks:c8_redstone_block>, <item:compressedblocks:c8_redstone_block>, <item:kubejs:compressed_compression_block>, <item:lava:infinity_shard>, <item:kubejs:compressed_compression_block>], 
	[<item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:compressedblocks:c8_redstone_block>, <item:compressedblocks:c8_redstone_block>, <item:compressedblocks:c8_redstone_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>, <item:kubejs:compressed_compression_block>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);