<recipetype:extendedcrafting:table>.addShaped("e3e920fa-8d76-4dbe-ad40-9b8a2d6407a5", 0, <item:extendedcrafting:the_ultimate_ingot>, [
	[<item:enderio:energetic_alloy_ingot>, <item:enderio:vibrant_alloy_ingot>, <item:enderio:redstone_alloy_ingot>, <item:enderio:conductive_alloy_ingot>, <item:enderio:pulsating_alloy_ingot>, <item:enderio:dark_steel_ingot>, <item:enderio:soularium_ingot>, <item:enderio:end_steel_ingot>, <item:eternal_starlight:aethersent_ingot>], 
	[<item:eternal_starlight:thermal_springstone_ingot>, <item:eternal_starlight:swamp_silver_ingot>, <item:eternal_starlight:amaramber_ingot>, <item:eternal_starlight:golem_steel_ingot>, <item:eternal_starlight:oxidized_golem_steel_ingot>, <item:industrialforegoing:pink_slime_ingot>, <item:silentgear:custom_ingot>.withJsonComponent(<componenttype:silentgear:material>, {material: "silentgear:high_carbon_steel", item: {count: 1, components: {"silentgear:material": {material: "silentgear:high_carbon_steel"}}, id: "silentgear:custom_ingot"}}), <item:silentgear:bronze_ingot>, <item:silentgear:crimson_iron_ingot>], 
	[<item:silentgear:crimson_steel_ingot>, <item:silentgear:blaze_gold_ingot>, <item:silentgear:azure_silver_ingot>, <item:silentgear:azure_electrum_ingot>, <item:silentgear:tyrian_steel_ingot>, <item:naturesaura:infused_iron>, <item:naturesaura:sky_ingot>, <item:naturesaura:tainted_gold>, <item:naturesaura:depth_ingot>], 
	[<item:pneumaticcraft:ingot_iron_compressed>, <item:megacells:sky_steel_ingot>, <item:megacells:sky_bronze_ingot>, <item:megacells:sky_osmium_ingot>, <item:aquaculture:neptunium_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_redstone_ingot>, <item:extendedcrafting:ender_ingot>], 
	[<item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:bigreactors:yellorium_ingot>, <item:bigreactors:blutonium_ingot>, <item:advanced_ae:quantum_alloy_plate>, <item:bigreactors:magentite_ingot>, <item:bigreactors:ludicrite_ingot>, <item:bigreactors:ridiculite_ingot>, <item:bigreactors:inanite_ingot>], 
	[<item:bigreactors:insanite_ingot>, <item:justdirethings:ferricore_ingot>, <item:justdirethings:blazegold_ingot>, <item:moremekanismprocessing:desh_ingot>, <item:justdirethings:eclipsealloy_ingot>, <item:alltheores:aluminum_ingot>, <item:alltheores:lead_ingot>, <item:alltheores:uranium_ingot>, <item:alltheores:constantan_ingot>], 
	[<item:moremekanismprocessing:draconium_ingot>, <item:alltheores:brass_ingot>, <item:moremekanismprocessing:lithium_ingot>, <item:alltheores:nickel_ingot>, <item:alltheores:platinum_ingot>, <item:alltheores:enderium_ingot>, <item:alltheores:bronze_ingot>, <item:alltheores:silver_ingot>, <item:alltheores:steel_ingot>], 
	[<item:alltheores:invar_ingot>, <item:alltheores:zinc_ingot>, <item:xycraft_world:aluminum_ingot>, <item:mysticalagriculture:prosperity_ingot>, <item:mysticalagriculture:inferium_ingot>, <item:mysticalagriculture:prudentium_ingot>, <item:mysticalagriculture:tertium_ingot>, <item:mysticalagriculture:imperium_ingot>, <item:mysticalagriculture:supremium_ingot>], 
	[<item:mysticalagriculture:awakened_supremium_ingot>, <item:mysticalagradditions:insanium_ingot>, <item:mekanism:ingot_bronze>, <item:mekanism:ingot_refined_obsidian>, <item:mekanism:ingot_refined_glowstone>, <item:twilightforest:ironwood_ingot>, <item:twilightforest:knightmetal_ingot>, <item:minecraft:netherite_ingot>, <item:bigreactors:cyanite_ingot>]
]);
